### ISSUE TITLE
Will this work with react instead of angular?

### ISSUE THREAD

**Issue by sagardesai90** [gavinsawyer/ngx-firebase-web-authn#1]
Am trying to get this to work with a react app, and seeing some issues with the angular node_modules.

Will this work with react? Thanks!

**Comment by gavinsawyer** [comment]
Initially I wrote this as an Angular service, but now there's no reason it shouldn't work with React. I was thinking I'd just have to change all the imports to `@firebase/xyz` instead of `@angular/fire/xyz`.

**Comment by sagardesai90** [comment]
Thanks for the quick reply! Going to try now, will let you know how it goes

**Comment by gavinsawyer** [comment]
15.6.1 Removed Angular dependencies from the browser library. Should work now!

**Comment by sagardesai90** [comment]
Looks like it's going to work, thanks @gavinsawyer

**Comment by gavinsawyer** [comment]
@sagardesai90 Since it's not using any Angular anymore, I released it as `firebase-web-authn` v9 instead. There's no changes but I'm only gonna maintain further by tracking the Firebase JavaScript API version on that new repo.

**Comment by sagardesai90** [comment]
thanks for the heads up, would you recommend using `npm install @firebase-web-authn/browser --save` for non angular use cases like mine?

**Comment by sagardesai90** [comment]
Not sure if you've seen this particular issue, seen after adding the following line as imports to my signup page:

`import { createUserWithPasskey, signInWithPasskey, verifyUserWithPasskey } from "@ngx-firebase-web-authn/browser";`


I thought I'd see an issue after calling createUserWithPasskey but it seems like its occurring before the components even load on the page.

<img width="454" alt="Screenshot 2023-04-02 at 9 55 51 AM" src="https://user-images.githubusercontent.com/24217185/229367426-5f7cdba4-4c5d-4d6f-9fdd-2eaf92656010.png">

**Comment by gavinsawyer** [comment]
> thanks for the heads up, would you recommend using `npm install @firebase-web-authn/browser --save` for non angular use cases like mine?

Yeah just so it's consistent with your `firebase` version which should also be ^9, but there are no changes aside from renaming the library. It'll deploy a new Firebase Function, call a different endpoint (`/firebaseWebAuthn`), and use a different collection in Firestore (`webAuthnUsers`)

**Comment by gavinsawyer** [comment]
> Not sure if you've seen this particular issue, seen after adding the following line as imports to my signup page:
> 
> `import { createUserWithPasskey, signInWithPasskey, verifyUserWithPasskey } from "@ngx-firebase-web-authn/browser";`
> 
> I thought I'd see an issue after calling createUserWithPasskey but it seems like its occurring before the components even load on the page.
> 
> <img alt="Screenshot 2023-04-02 at 9 55 51 AM" width="454" src="https://user-images.githubusercontent.com/24217185/229367426-5f7cdba4-4c5d-4d6f-9fdd-2eaf92656010.png">

Not sure sorry but seems like something that might be solved with `% rm package-lock.json && npm install`.

**Comment by sagardesai90** [comment]
Just tried `rm package-lock.json && npm install` and saw the same result as before, going to see in a bit as to what it might be, thanks for the help!

**Comment by sagardesai90** [comment]
@gavinsawyer been trying to figure out why its giving the same issue as above upon import. The way the error message is written makes it seem like it expects a credential, but I haven't called the function anywhere. Could it be because of something that happens while the package gets imported? 


<img width="815" alt="Screenshot 2023-04-03 at 3 04 33 PM" src="https://user-images.githubusercontent.com/24217185/229637958-2e722dc7-dd6f-4553-a7d1-2d2da802fb9c.png">
<img width="764" alt="Screenshot 2023-04-03 at 3 03 55 PM" src="https://user-images.githubusercontent.com/24217185/229637962-7ec2af42-8b43-4fb9-8645-5a9f4256c77c.png">

**Comment by sagardesai90** [comment]
Could it be because I haven't done the part for [@firebase-web-authn/functions](https://github.com/gavinsawyer/firebase-web-authn/blob/main/libs/functions), including the setup for [@firebase-web-authn/functions](https://github.com/gavinsawyer/firebase-web-authn/blob/main/libs/functions)?  I didn't think it'd be this because asking for credentials locally wouldn't affect anything on firebase right away.

**Comment by gavinsawyer** [comment]
> Could it be because I haven't done the part for [@firebase-web-authn/functions](https://github.com/gavinsawyer/firebase-web-authn/blob/main/libs/functions), including the setup for [@firebase-web-authn/functions](https://github.com/gavinsawyer/firebase-web-authn/blob/main/libs/functions)? I didn't think it'd be this because asking for credentials locally wouldn't affect anything on firebase right away.

No, that shouldn't be what's causing the issue. I looked into babel and how to solve an issue I was having where Angular displayed a warning about using commonjs modules. Turns out I should have been publishing es6. Please let me know if firebase-web-authn@9.1.5 fixed this for you.

See https://bundlephobia.com/package/@firebase-web-authn/browser@9.1.5 (tree-shakeable now appears)

**Comment by sagardesai90** [comment]
@gavinsawyer thanks for checking in, I just tried again with 9.1.5, and its showing the same issue. Really excited to get it working though, webauthn will be a great compliment to the rest of what I've got.

**Comment by gavinsawyer** [comment]
You’re not using react native or any environment without a window context are you? I moved the types to a new lib out of the functions lib, so if the problem was commonjs that should be fixed. The error snippet you gave isn’t coming from code I wrote though so I’m not sure what I can do.
